### ISSUE TITLE
Unable to replace bundled .csv with my own data

### ISSUE THREAD

**Issue by laynic** [nizos/After-Effects-CSV-Line-Graph#1]
Love the software idea, but any variation of an attempt to use my own data has failed (including trying to alter the sample data). I'm sure I'm doing something wrong, but don't know where else to ask for advice. Thanks in advance!

**Comment by nizos** [comment]
@nist4150 I will download After Effects and try it again tomorrow. Feel free to link to a gist with your data if you want me to try it. 😊

**Comment by laynic** [comment]
That would be awesome, thanks! For this project I was using "falsified" data (I.e. random numbers inserted into a csv in the same format as the sample file) to see if I could accomplish my animation goal; I won't have the actual data for another few weeks. This is the data I was trying to throw in (and replace Sample 1 with):

I should also note that it all worked just fine with your example if I didn't touch anything and just let it run, so I don't think there's an issue with the program, I think I'm just missing something painfully obvious.
[Sample1(altered).csv](https://github.com/nizos/After-Effects-CSV-Line-Graph/files/6819287/Sample1.altered.csv)

**Comment by nizos** [comment]
@nist4150 You can try doing this until I can test it myself:
1. Download a new copy of the project.
2. Replace the csv file before opening the project.
3. Open the project and start the render.

There are two things that I can think of:
The first row of a csv file is the names of the columns. Maybe you need to have them in your file too. (Time, Value).
The second thing is the X axis data. Maybe it only accepts time in the format I used for the first column. Try that if everything doesn't work.

The final thing I can recommend for troubleshooting, use a new copy of the project if you want to try different csv data and make sure to replace the csv files before opening the project the first time. I think After Effects might be storing the data somewhere else behind the scenes after it creates footage out of it when it is imported. I could be wrong, I haven't used it in two years but this is what I would try. 😊

**Comment by nizos** [comment]
@nist4150 Also try not to change the name of the file. Maybe that's also hard coded.

**Comment by laynic** [comment]
Sorry for the late response; I fell ill but I'm back on it. Your idea worked; changing the data before I launched the project rendered a successful graph. Thanks for your help!

**Comment by nizos** [comment]
@nist4150 No worries! I am glad that you got it to work. I will add some information about this issue to the README.md document as well. I will close the issue now since it has been resolved. 😊
